skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
svi_mock_adapter = "3kK7593G5wN5R9S9Sce5zVAy2BuijtMEFwzUCjh3oW8M"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
